### ISSUE TITLE
Invalid TOML

### ISSUE THREAD

**Issue by LKedward** [urbanjost/M_CLI#2]
Hi @urbanjost,
I'm doing some work (<https://github.com/fortran-lang/fpm-registry/issues/11>) on the [fpm-registry](https://github.com/fortran-lang/fpm-registry/) in order to get fpm packages listed on the website.

As part of this I've been parsing `fpm.toml` files from each package in the registry and I've noticed that M_CLI uses an invalid TOML syntax. Though Haskell fpm doesn't complain about this, it is causing some issues when parsing the TOML in Python.

According to [the spec](https://toml.io/en/v1.0.0-rc.1#keyvalue-pair), there must be a newline after each key/value pair.
I believe the minimal syntax you are looking for can be achieved with _inline tables_, see [here](https://toml.io/en/v1.0.0-rc.1#filename-extension) (scroll up slightly).

If I get time later, I can put together a pull request.

**Comment by LKedward** [comment]
For you own reference, here's a stand-alone script to verify TOML in Python:
```python
import sys, toml

filename = 'fpm.toml'
with open(filename, 'r') as myfile:
            data=myfile.read()

p = toml.loads(data)
print(p)
```

`toml.loads()` will fail with an exception in the TOML is invalid.

**Comment by urbanjost** [comment]
Thanks.  Problem is I wrote about ten of them the same way, so I need to re-apply your changes. fpm(1) appeared to work fine with them the way they wer with the fpm(1) version I currently have so I would not have noticed till fpm(1) refused to read them, I suspect.

**Comment by urbanjost** [comment]
Thanks. I pulled the changes. I need to track down the python::toml package or some other toml tools to valid others; which I suspect also have issues. First use of toml, I'm afraid. I was trusting fpm(1) to validate it.

**Comment by LKedward** [comment]
Sounds good. Sorry, for some reason I'd thought `toml` was a built-in Python package - you'll need to fetch it with `pip` or similar.
It's a defect in the Haskell `toml` package that caused it; I will be sure to check the new Fortran implementation when it is ready.

Also any `fpm. toml` issues are now automatically detected if you submit your package to <https://github.com/fortran-lang/fpm-registry>.
